### ISSUE TITLE
unwanted linebreak in refinery.lua line 393 and 400, minetest.log

### ISSUE THREAD

**Issue by Festus1965** [Lokrates/Biofuel#13]
unwanted line break to minetest.log
in refinery.lua line 393
minetest.log('action', player:get_player_name() .. S(" moves stuff to refinery at ") .. minetest.pos_to_string(pos))
and line 400
minetest.log('action', player:get_player_name() .. S(" takes stuff from refinery at ") .. minetest.pos_to_string(pos))

output

`2021-05-06 12:44:08: ACTION[Server]: Thorviss(T@biofuel) takes stuff from refinery at 
(17640,-9,23806)
`

and I don't see how to avoid it.
Is not so nice when the coordinates are in the next line without need.
Also not nice sign/item after player ...

**Comment by Lokrates** [comment]
Should be fixed with version 0.7.
