### ISSUE TITLE
Minor issue causing warnings in MT 5.5.0 with texture alpha clipping

### ISSUE THREAD

**Issue by Baigle** [Lokrates/Biofuel#18]
Posting because I have thousands of messages in my debug.txt about these, and I now see them after I allowed warning-level messages in chat. It won't be an issue until they require it to be set in the future.

> WARNING[Main]:   This warning can be a false-positive if unused pixels in the texture are transparent. However if it is meant to be transparent, you *MUST* update the nodedef and set use_texture_alpha = "clip"! This compatibility code will be removed in a few releases.

The affected textures are: 

> "biofuel_fr_active.png" of biofuel:refinery_active
"biofuel_fr.png" of biofuel:refinery

**Comment by Lokrates** [comment]
Should be fixed with version 0.7.
